### ISSUE TITLE
No sound using qt5 branch

### ISSUE THREAD

**Issue by barjac** [hardaker/CuteCW#10]
I just tried a re-package of cutecw in Mageia cauldron using your 'convert-to-qt5'  branch - and while it builds fine there is no sound at all (with or without pulesaudio enabled).

[baz@jackodesktop ~]$ cutecw
xkbcommon: ERROR: failed to add default include path auto
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
Raw audio format not supported by backend, cannot play audio.
new morse2
original buffer size:  0
switch to: 0
QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout  
QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout  
Raw audio format not supported by backend, cannot play audio.  
using null output device, none available
# --------------------------------------------

Backend is Phonon Gstreamer 4.7.1

Any ideas?

Barry

**Comment by daryltucker** [comment]
You didn't find a solution, did you @barjac ?
Thanks.

**Comment by barjac** [comment]
No sorry - I have been using CW Studio which works fine.
Also sorry for the long delay - I just fell across this while browsing!

**Comment by rhaamo** [comment]
I finished porting CuteCW to Qt5 in my fork (https://github.com/rhaamo/CuteCW) and have been using it a few times and no issues with sound.

**Comment by barjac** [comment]
Ah - OK, thanks. I have pushed the 1.2 release to our dev branch and running under plasma5 with pulseaudio there is sound. However there are issues with some character's sound being truncated so that 'u' is received as 's' etc. The truncation coincides with a click in the sound output.
You can see my response with 's' to a 'u':
[2017-10-22T00:17:41][D][modes/LetterTrainingMode.cpp:70 (LetterTrainingMode::startNextTrainingKey)] --- Start next training key
[2017-10-22T00:17:41][D][modes/LetterTrainingMode.cpp:104 (LetterTrainingMode::startNextTrainingKey)] |keying:  'u'
[2017-10-22T00:17:41][D][MorseStat.cpp:24 (MorseStat::getGoodPercentage)] not good enough:  8 / 10
[2017-10-22T00:17:42][D][modes/TrainingMode.cpp:170 (TrainingMode::audioStopped)] audio stopped
[2017-10-22T00:17:42][D][modes/TrainingMode.cpp:181 (TrainingMode::handleKeyPress)] Key pressed =  's' , Queue of stored keys: keys= 1 , times= 1

**Comment by barjac** [comment]
Sorry to say that while there is audio in plasma5 now in both 64 and 32 bit builds, there is none in 32 bit LXDE or XFCE DEs. Same 'Raw audio format not supported by backend, cannot play audio.' error.
This is using:
pulseaudio-10.0
qt5 5.6.2

**Comment by rhaamo** [comment]
I don't know about the sounds cutted, I don't remember having or got feedbacks about that but I'm open to integrate fixes.

About the 'no audio', IIRC you need more packages for this, the debian package requires theses ones:
```
libqt5multimedia5 libqt5multimedia5-plugins
```
Can you check you have them ?

**Comment by barjac** [comment]
I saw that Debian packages libqt5multimedia5-plugins, but I maintain cutecw for Mageia and we don't have that package. Everything in the Debian libqt5multimedia5-plugins package is included in our qt5multimedia5 package. 
Our bug report on this may have something to help:
https://bugs.mageia.org/show_bug.cgi?id=21911

**Comment by barjac** [comment]
OK I found the issue in our packaging - I thought I had checked this but it seems that the required libs are in our qtmultimedia5 package which is not installed by default in DE's other than plasma5 and for some reason it was not being rpm auto-required either by cutecw. Sorry for the noise and thanks for making me look again at the deps :)
The truncated sounds in the other bug however are still an issue :(

**Comment by hardaker** [comment]
The main branch is now hopefully stable again and works with qt6.  This should fix everyone's issues I hope.  I think there may still a bug in windows.
