### ISSUE TITLE
N900 - Recognition Training lacks accuracy feedback

### ISSUE THREAD

**Issue by ijk** [hardaker/CuteCW#7]
The screenshots for the Linux version look great. 
N900 Suggestions:
Make the touchscreen keyboard  disappear when the hardware keyboard is open to be replaced with accuracy graphs.
Have a button that switches between touchscreen keyboard and the graphs.
Change the appearance of the touchscreen keys based on accuracy.

great program btw :-)

**Comment by hardaker** [comment]
So the n900 unfortunately is pretty much gone.  Sadness; awesome phone.
